import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { createCipheriv, createHash, randomBytes } from "node:crypto";
import { cardlessCredentialPayloadHash, matchesCardlessCredentialPayloadHash, encryptCardlessCredential, decryptCardlessCredential } from "./cardless-credential-crypto";

const oldSecret = "legacy-service-role-material-for-test-only";
const newSecret = "dedicated-encryption-material-for-test-only";
const payload = JSON.stringify({ withdrawalCode: "987654", verificationValue: "123456789" });

beforeEach(() => {
  vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", "");
  vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_PREVIOUS_SECRET", "");
  vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_ACTIVATE_AT", "");
  vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY", oldSecret);
  vi.stubEnv("SUPABASE_DB_URL", "");
});
afterEach(() => { vi.unstubAllEnvs(); vi.useRealTimers(); });

describe("Cardless ATM key migration", () => {
  it("reads ciphertext generated by the original implementation after adding the dedicated key", () => {
    const key = createHash("sha256").update(`alpha-exchange-cardless-v1\0${oldSecret}`).digest();
    const iv = randomBytes(12);
    const cipher = createCipheriv("aes-256-gcm", key, iv);
    cipher.setAAD(Buffer.from("request\0message"));
    const ciphertext = Buffer.concat([cipher.update(payload), cipher.final()]);
    const legacy = `cardless:v1:${iv.toString("base64url")}:${cipher.getAuthTag().toString("base64url")}:${ciphertext.toString("base64url")}`;
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    expect(decryptCardlessCredential(legacy, "request", "message")).toBe(payload);
  });

  it("uses the dedicated key for new writes and preserves old duplicate checks", () => {
    const oldHash = cardlessCredentialPayloadHash("request", payload);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    expect(matchesCardlessCredentialPayloadHash(oldHash, "request", payload)).toBe(true);
    expect(matchesCardlessCredentialPayloadHash(oldHash, "other-request", payload)).toBe(false);
    expect(matchesCardlessCredentialPayloadHash(oldHash, "request", `${payload}changed`)).toBe(false);
    expect(cardlessCredentialPayloadHash("request", payload)).not.toBe(oldHash);
    const encrypted = encryptCardlessCredential(payload, "request", "message");
    expect(encrypted).not.toContain("987654");
    vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY", "");
    expect(decryptCardlessCredential(encrypted, "request", "message")).toBe(payload);
  });

  it("supports a previous dedicated key when rotating again", () => {
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    const encrypted = encryptCardlessCredential(payload, "request", "message");
    const hash = cardlessCredentialPayloadHash("request", payload);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_PREVIOUS_SECRET", newSecret);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", "next-dedicated-key-material-for-test-only");
    expect(decryptCardlessCredential(encrypted, "request", "message")).toBe(payload);
    expect(matchesCardlessCredentialPayloadHash(hash, "request", payload)).toBe(true);
  });

  it("preserves the database-URL fallback even if a service key is subsequently configured", () => {
    vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY", "");
    vi.stubEnv("SUPABASE_DB_URL", "postgres://legacy-test-connection");
    const encrypted = encryptCardlessCredential(payload, "request", "message");
    vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY", oldSecret);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    expect(decryptCardlessCredential(encrypted, "request", "message")).toBe(payload);
  });

  it("stages reads before the timed write-key switch", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-09-23T00:00:00Z"));
    const oldHash = cardlessCredentialPayloadHash("request", payload);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_ACTIVATE_AT", "2026-09-23T13:00:00Z");
    expect(cardlessCredentialPayloadHash("request", payload)).toBe(oldHash);
    const staged = encryptCardlessCredential(payload, "request", "message");
    vi.setSystemTime(new Date("2026-09-23T13:00:00Z"));
    expect(cardlessCredentialPayloadHash("request", payload)).not.toBe(oldHash);
    expect(decryptCardlessCredential(staged, "request", "message")).toBe(payload);
    const active = encryptCardlessCredential(payload, "request", "message");
    vi.setSystemTime(new Date("2026-09-23T12:59:00Z"));
    expect(decryptCardlessCredential(active, "request", "message")).toBe(payload);
  });

  it("rejects altered ciphertext, tags, IVs, and cross-trade replay", () => {
    const encrypted = encryptCardlessCredential(payload, "request", "message");
    expect(decryptCardlessCredential(encrypted, "other", "message")).toBeNull();
    expect(decryptCardlessCredential(encrypted, "request", "other")).toBeNull();
    const parts = encrypted.split(":");
    for (const index of [2, 3, 4]) {
      const altered = [...parts];
      altered[index] = (altered[index][0] === "A" ? "B" : "A") + altered[index].slice(1);
      expect(decryptCardlessCredential(altered.join(":"), "request", "message")).toBeNull();
    }
    expect(decryptCardlessCredential(`${encrypted}:extra`, "request", "message")).toBeNull();
  });

  it("fails closed on weak keys or malformed activation settings", () => {
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", "weak");
    expect(() => encryptCardlessCredential(payload, "request", "message")).toThrow("32 characters");
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_SECRET", newSecret);
    vi.stubEnv("ALPHA_EXCHANGE_CARDLESS_CREDENTIAL_ACTIVATE_AT", "invalid-date");
    expect(() => encryptCardlessCredential(payload, "request", "message")).toThrow("activation is invalid");
  });
});
