export const MAX_ACTIVE_LISTINGS_PER_SELLER = 2;
export const COMMISSION_RATE = 0.01;
export const COMMISSION_GRACE_PERIOD_DAYS = 7;
export const DEFAULT_LISTING_EXPIRATION_HOURS = 24;
export const ALLOWED_LISTING_EXPIRATION_HOURS = [1, 6, 12, 24] as const;
export const DEFAULT_STALE_TRADE_TIMEOUT_MINUTES = 20;
export const BUYER_CONFIRMATION_TIMEOUT_MINUTES = 5;
