import { text as t, type FirmProgram, type PropFirm } from "./types";
const sources = [
  {title:"CFD trading objectives",url:"https://ftmo.com/en/trading-objectives/"},
  {title:"1-Step vs 2-Step",url:"https://ftmo.com/en/comparison-table/"},
  {title:"Rewards, methods & timing",url:"https://ftmo.com/en/faq/how-do-i-withdraw-my-profits/"},
  {title:"Current prices",url:"https://ftmo.com/en/"},
];
const programs:FirmProgram[] = [false,true].map(one=>({
  id:one?"one-step":"two-step",name:one?"CFD · 1-Step":"CFD · 2-Step",
  tagline:one?t("One evaluation · 90% reward share","امتحان واحد · حصة مكافأة 90%"):t("Challenge + Verification · 80% base share","Challenge ثم Verification · حصة أساسية 80%"),
  tiers:[10000,25000,50000,100000,200000].map(size=>({size,targets:one?[size*.1]:[size*.1,size*.05],maxLoss:size*.1,dailyLoss:size*(one?.03:.05),minPayout:20,buffer:0})),
  evaluationDays:one?t("No separate minimum-day rule; Best Day rule still applies","دون شرط أيام منفصل؛ قاعدة أفضل يوم تبقى مطلوبة"):t("4 trading days in each evaluation phase","4 أيام تداول بكل مرحلة من الامتحان"),
  evaluationConsistency:one?t("Best day ≤50% of the sum of POSITIVE days' profits. Applies in evaluation and when requesting rewards.","أفضل يوم ≤50% من مجموع أرباح الأيام الموجبة. تُطبّق بالامتحان وعند طلب المكافأة."):t("No Best Day rule on 2-Step","لا توجد قاعدة أفضل يوم في 2-Step"),
  drawdown:one?t("10% EOD trailing maximum loss. Daily loss is 3% of initial capital from the midnight CE(S)T balance baseline.","خسارة قصوى 10% متحركة بنهاية اليوم. الخسارة اليومية 3% من رأس المال الابتدائي، انطلاقاً من رصيد منتصف الليل CE(S)T."):t("10% static maximum loss. Daily loss is 5% of initial capital, including floating P/L, commissions and swaps; resets at midnight CE(S)T.","خسارة قصوى ثابتة 10%. اليومية 5% من رأس المال الابتدائي، وتشمل الربح والخسارة المفتوحة والعمولات والسواب؛ تتجدد بمنتصف الليل CE(S)T."),
  pricing:t("One-time evaluation fee. The official selector quotes the final price for size, product and currency; use that quote instead of an outdated fixed conversion.","رسوم امتحان مرة واحدة. الاختيار الرسمي يعرض السعر النهائي حسب الحجم والمنتج والعملة؛ اعتمد هذا السعر بدل تحويل عملات أو سعر قديم."),
  activation:one?t("After passing: results review, FTMO Identity and account agreement. Check the specific order's fee-refund terms.","بعد النجاح: مراجعة النتائج، FTMO Identity واتفاقية الحساب. راجع شروط استرداد الرسوم الخاصة بطلبك."):t("Pass both phases, complete FTMO Identity and sign the account agreement. The 2-Step fee is refundable with the first reward under its terms.","انجح بالمرحلتين، أكمل FTMO Identity ووقّع اتفاقية الحساب. رسوم 2-Step تُسترد مع أول مكافأة حسب الشروط."),
  funded:[t("The FTMO Account remains simulated; rewards are real-money payments under the agreement. There is no funded profit target, but the loss rules continue.","FTMO Account يبقى حساب محاكاة؛ المكافأة دفعة مالية حقيقية حسب الاتفاقية. لا يوجد هدف ربح بالمموّل، لكن حدود الخسارة تستمر."),one?t("1-Step offers Standard only. Rewards cannot be rolled over to grow the account balance.","1-Step متاح بنوع Standard فقط. لا يمكن ترك المكافأة لزيادة رصيد الحساب."):t("2-Step offers Standard and Swing. Base reward share is 80%, increasing to 90% when scaling/premium conditions are met. Eligible rewards may be rolled over.","2-Step فيه Standard وSwing. الحصة الأساسية 80% وتزيد إلى 90% عند استيفاء شروط التطوير أو البرنامج المميز. يمكن ترك المكافآت المؤهلة بالحساب.")],
  payoutDetails:[
    t("Request on day 14 or later after the first trade on the FTMO Account. Close all positions and pending orders. No need to repeat the evaluation profit target.","اطلب في اليوم 14 أو بعده من أول صفقة على FTMO Account. أغلق كل الصفقات والأوامر المعلّقة. لا يلزم تكرار هدف ربح الامتحان."),
    t("Bank wire requires at least $20 closed profit; crypto requires $50. The payout estimate uses the amount approved as available in Account MetriX and your actual reward ratio.","الحوالة البنكية تحتاج ربحاً مغلقاً $20 على الأقل؛ الكريبتو $50. تقدير السحب يستخدم المبلغ المتاح في Account MetriX ونسبة مكافأتك الفعلية."),
  ],
  cautions:[t("This guide covers FTMO CFD products. FTMO Futures is a separate product. Standard/Swing, selected news restrictions and weekend rules must match the account you purchased.","هذا الدليل لمنتجات FTMO CFD. FTMO Futures منتج منفصل. نوع Standard/Swing وقيود الأخبار ونهاية الأسبوع لازم تطابق الحساب الذي اشتريته."),t("For 1-Step, positive-day profit is NOT the same as net profit after losing days. Do not calculate its 50% rule using a futures firm's denominator.","في 1-Step مجموع أرباح الأيام الموجبة ليس صافي الربح بعد الأيام الخاسرة. لا تحسب قاعدة 50% بنفس طريقة شركات الفيوتشرز.")],
  payout:{mode:"dashboard",share:one?90:80,days:0,calendarDays:14},sources,
}));
export const ftmo:PropFirm = {
  slug:"ftmo",name:"FTMO",short:"FTMO",accent:"#77A8FF",market:t("Forex & CFDs","فوركس وعقود فروقات"),website:"https://ftmo.com/en/",
  description:t("Compare 1-Step and 2-Step: targets, daily loss, reward ratio and the Best Day rule.","قارن 1-Step و2-Step: الأهداف، الخسارة اليومية، نسبة المكافأة وقاعدة أفضل يوم."),programs,
  receiving:[t("Account MetriX → request Reward → account review → enter payment details in FTMO Traders → invoice approval and payment.","Account MetriX ← طلب Reward ← مراجعة الحساب ← إدخال بيانات الاستلام في FTMO Traders ← اعتماد الفاتورة والدفع."),t("Review usually takes 1–2 business days; payment is typically sent 1–2 business days after invoice approval. Bank arrival can take additional time.","المراجعة عادةً 1–2 يوم عمل؛ تُرسل الدفعة عادةً بعد 1–2 يوم عمل من اعتماد الفاتورة. وصولها للبنك قد يحتاج وقتاً إضافياً."),t("Bank wire, crypto, Visa Direct/Mastercard Send (up to $20,000), or Skrill (up to $3,000), subject to availability. FTMO adds no withdrawal commission; provider and conversion costs may differ.","حوالة بنكية، كريبتو، Visa Direct/Mastercard Send (حتى $20,000)، أو Skrill (حتى $3,000)، حسب التوفر. FTMO لا تضيف عمولة سحب؛ رسوم المزوّد والتحويل ممكن تختلف.")],
  important:[t("USD account sizes are shown here. Buying power is not a cash deposit you can withdraw. Your exact agreement and Account MetriX determine reward availability.","الأحجام هنا لحسابات بالدولار. القوة الشرائية ليست وديعة نقدية قابلة للسحب. الاتفاقية وAccount MetriX يحددان المكافأة المتاحة.")],sources,
};
