import { NextRequest, NextResponse } from "next/server";

// Keep TradingView's official embed in a sandboxed document. No vendor script
// runs in the account page, and no calendar data is copied into our news API.
export function GET(request: NextRequest) {
  const isAr = request.nextUrl.searchParams.get("locale") === "ar";
  const locale = isAr ? "ar_AE" : "en";
  const calendarUrl = isAr ? "https://ar.tradingview.com/economic-calendar/" : "https://www.tradingview.com/economic-calendar/";
  const config = JSON.stringify({
    colorTheme: "dark", isTransparent: false, locale, countryFilter: "us",
    // Generated by TradingView's "Only high importance" setting.
    importanceFilter: "0,1", width: "100%", height: "100%",
  });
  const html = `<!doctype html>
<html lang="${isAr ? "ar" : "en"}" dir="${isAr ? "rtl" : "ltr"}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${isAr ? "تقويم أخبار الدولار" : "USD economic calendar"}</title>
<style>html,body{margin:0;width:100%;height:100%;background:#131722;font-family:Arial,sans-serif}.tradingview-widget-container{width:100%;height:100%}.tradingview-widget-container__widget{height:calc(100% - 32px)}.tradingview-widget-copyright{font-size:12px;line-height:32px;text-align:center;color:#9ca3af}.blue-text{color:#90bff9}a{color:#90bff9}</style>
</head><body>
<div class="tradingview-widget-container">
<div class="tradingview-widget-container__widget"></div>
<div class="tradingview-widget-copyright"><a href="${calendarUrl}" rel="noopener nofollow" target="_blank"><span class="blue-text">${isAr ? "التقويم الاقتصادي" : "Economic Calendar"}</span></a><span class="trademark"> by TradingView</span></div>
<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-events.js" async>${config}</script>
</div></body></html>`;
  return new NextResponse(html, { headers: {
    "Content-Type": "text/html; charset=utf-8",
    "Cache-Control": "public, max-age=300, s-maxage=3600",
    "X-Frame-Options": "SAMEORIGIN",
    "X-Robots-Tag": "noindex, nofollow",
    "Referrer-Policy": "origin",
    "Content-Security-Policy": [
      "default-src 'none'",
      "script-src https://s3.tradingview.com/external-embedding/embed-widget-events.js",
      "style-src 'unsafe-inline'",
      "img-src data: https://s3.tradingview.com",
      "frame-src https://www.tradingview-widget.com https://tradingview-widget.com",
      "frame-ancestors 'self'",
      "sandbox allow-scripts allow-popups allow-popups-to-escape-sandbox",
      "base-uri 'none'", "form-action 'none'", "object-src 'none'",
    ].join("; "),
  } });
}
