// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/about-founder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about-founder">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about-founder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/academy/[course]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/academy/[course]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/academy/[course]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/academy/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/academy/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/academy/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/academy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/alpha-exchange/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/alpha-exchange">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/alpha-exchange/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/alpha-exchange/pending-listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/alpha-exchange/pending-listings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/alpha-exchange/pending-listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/community">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/dashboard/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/seller">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/dashboard/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/founder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/founder">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/founder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/lessons/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/lessons/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/lessons/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/lessons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/lessons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/register">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/usdt-exchange/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/usdt-exchange">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/usdt-exchange/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/lessons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/lessons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/versions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin-prep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin-prep">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin-prep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/listings/[listingId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/listings/[listingId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/listings/[listingId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/pending-listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/pending-listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/pending-listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/private-beta/announcements/[announcementId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/private-beta/announcements/[announcementId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/private-beta/announcements/[announcementId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/private-beta/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/private-beta/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/private-beta/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/private-beta/feedback/[feedbackId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/private-beta/feedback/[feedbackId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/private-beta/feedback/[feedbackId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/private-beta/invites/[inviteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/private-beta/invites/[inviteId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/private-beta/invites/[inviteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/private-beta/invites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/private-beta/invites">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/private-beta/invites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/seller-applications/[applicationId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/seller-applications/[applicationId]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/seller-applications/[applicationId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/seller-applications/[applicationId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/seller-applications/[applicationId]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/seller-applications/[applicationId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/seller-applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/seller-applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/seller-applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/sellers/[userId]/profile-state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/sellers/[userId]/profile-state">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/sellers/[userId]/profile-state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/sellers/[userId]/reactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/sellers/[userId]/reactivate">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/sellers/[userId]/reactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/admin/sellers/[userId]/suspend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/admin/sellers/[userId]/suspend">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/admin/sellers/[userId]/suspend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/listings/[listingId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/listings/[listingId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/listings/[listingId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/my-listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/my-listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/my-listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/notification-preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/notification-preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/notification-preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/notifications/[notificationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/notifications/[notificationId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/notifications/[notificationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/private-beta/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/private-beta/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/private-beta/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/private-beta/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/private-beta/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/private-beta/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/purchase-requests/[requestId]/evidence/[evidenceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/purchase-requests/[requestId]/evidence/[evidenceId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/purchase-requests/[requestId]/evidence/[evidenceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/purchase-requests/[requestId]/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/purchase-requests/[requestId]/evidence">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/purchase-requests/[requestId]/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/purchase-requests/[requestId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/purchase-requests/[requestId]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/purchase-requests/[requestId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/purchase-requests/[requestId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/purchase-requests/[requestId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/purchase-requests/[requestId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/purchase-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/purchase-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/purchase-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/seller-application/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/seller-application">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/seller-application/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/seller-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/seller-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/seller-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha-exchange/sellers/[sellerId]/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha-exchange/sellers/[sellerId]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha-exchange/sellers/[sellerId]/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
