import type { MobileAcademyLevel, MobileLessonDifficulty, MobileLocale } from "@alpha-traders/contracts";

export const academyCopy = {
  en: {
    title: "Academy",
    subtitle: "Learn the complete Alpha Traders method in order, built for your phone.",
    learningPath: "Your learning path",
    continueLearning: "Continue learning",
    startLearning: "Start learning",
    resumeLesson: "Resume lesson",
    publishedLessons: "published lessons",
    courseProgress: "Course progress",
    lessonProgress: "Lesson progress",
    completed: "Completed",
    inProgress: "In progress",
    notStarted: "Not started",
    trackOverview: "Track overview",
    whatYouLearn: "What you will learn",
    whyStart: "Why begin with this track",
    openTrack: "Open track",
    openLesson: "Open lesson",
    emptyTitle: "No published lessons yet",
    emptyBody: "New Academy lessons will appear here when they are ready.",
    loadError: "The Academy could not be loaded.",
    contentUnavailable: "This lesson is not available right now.",
    backToAcademy: "Back to Academy",
    backToTrack: "Back to track",
    lesson: "Lesson",
    question: "Question",
    minutes: "minutes",
    duration: "Duration",
    difficulty: "Difficulty",
    overview: "Overview",
    lessonVideo: "Lesson video",
    openVideo: "Watch video",
    markVideoWatched: "Mark video as watched",
    videoCompleted: "Video watched",
    workbook: "Workbook",
    openWorkbook: "Open workbook",
    workbookOpened: "Workbook opened",
    presentation: "Presentation",
    openPresentation: "Open presentation",
    resources: "Lesson resources",
    lessonSummary: "Lesson summary",
    keyTakeaways: "Key takeaways",
    objectives: "Learning objectives",
    keyConcepts: "Key concepts",
    practicalExamples: "Practical examples",
    chartsExamples: "Charts and examples from the course",
    commonMistakes: "Common beginner mistakes",
    courseNotes: "Course notes",
    personalNotes: "My notes",
    personalNotesBody: "Saved only for this signed-in account on this device.",
    notesPlaceholder: "Write your lesson notes…",
    saveNotes: "Save notes",
    notesSaved: "Notes saved",
    bookmark: "Bookmark lesson",
    bookmarked: "Bookmarked",
    quiz: "Lesson quiz",
    quizBody: "Answer every question, then submit your quiz.",
    submitQuiz: "Submit quiz",
    retryQuiz: "Try quiz again",
    quizScore: "Quiz score",
    quizPassed: "Quiz passed",
    quizTryAgain: "Review the answers and try again.",
    selectEveryAnswer: "Choose an answer for every question.",
    correctAnswer: "Correct",
    incorrectAnswer: "Not quite",
    previousLesson: "Previous lesson",
    nextLesson: "Next lesson",
    completionReady: "All lesson requirements are complete.",
    completionPending: "Complete the remaining requirements shown below.",
    linkError: "This resource could not be opened safely.",
    cachedHint: "Previously loaded lessons remain available while offline.",
  },
  ar: {
    title: "الأكاديمية",
    subtitle: "تعلّم منهج ألفا تريدرز الكامل بالترتيب وبتجربة مصممة لهاتفك.",
    learningPath: "مسار التعلم الخاص بك",
    continueLearning: "متابعة التعلم",
    startLearning: "ابدأ التعلم",
    resumeLesson: "متابعة الدرس",
    publishedLessons: "دروس منشورة",
    courseProgress: "تقدم المسار",
    lessonProgress: "تقدم الدرس",
    completed: "مكتمل",
    inProgress: "قيد التقدم",
    notStarted: "لم يبدأ",
    trackOverview: "نظرة عامة على المسار",
    whatYouLearn: "ماذا ستتعلم",
    whyStart: "لماذا تبدأ بهذا المسار",
    openTrack: "فتح المسار",
    openLesson: "فتح الدرس",
    emptyTitle: "لا توجد دروس منشورة بعد",
    emptyBody: "ستظهر دروس الأكاديمية الجديدة هنا عندما تصبح جاهزة.",
    loadError: "تعذر تحميل الأكاديمية.",
    contentUnavailable: "هذا الدرس غير متاح الآن.",
    backToAcademy: "العودة إلى الأكاديمية",
    backToTrack: "العودة إلى المسار",
    lesson: "الدرس",
    question: "السؤال",
    minutes: "دقيقة",
    duration: "المدة",
    difficulty: "المستوى",
    overview: "نظرة عامة",
    lessonVideo: "فيديو الدرس",
    openVideo: "مشاهدة الفيديو",
    markVideoWatched: "تأكيد مشاهدة الفيديو",
    videoCompleted: "تمت مشاهدة الفيديو",
    workbook: "كراسة العمل",
    openWorkbook: "فتح كراسة العمل",
    workbookOpened: "تم فتح كراسة العمل",
    presentation: "العرض التقديمي",
    openPresentation: "فتح العرض التقديمي",
    resources: "مصادر الدرس",
    lessonSummary: "ملخص الدرس",
    keyTakeaways: "أهم النقاط",
    objectives: "أهداف التعلم",
    keyConcepts: "المفاهيم الأساسية",
    practicalExamples: "أمثلة عملية",
    chartsExamples: "الرسوم والأمثلة من الدورة",
    commonMistakes: "أخطاء المبتدئين الشائعة",
    courseNotes: "ملاحظات الدورة",
    personalNotes: "ملاحظاتي",
    personalNotesBody: "تُحفظ لهذا الحساب المسجّل فقط على هذا الجهاز.",
    notesPlaceholder: "اكتب ملاحظاتك عن الدرس…",
    saveNotes: "حفظ الملاحظات",
    notesSaved: "تم حفظ الملاحظات",
    bookmark: "حفظ الدرس",
    bookmarked: "محفوظ",
    quiz: "اختبار الدرس",
    quizBody: "أجب عن جميع الأسئلة ثم أرسل الاختبار.",
    submitQuiz: "إرسال الاختبار",
    retryQuiz: "إعادة الاختبار",
    quizScore: "نتيجة الاختبار",
    quizPassed: "تم اجتياز الاختبار",
    quizTryAgain: "راجع الإجابات وحاول مرة أخرى.",
    selectEveryAnswer: "اختر إجابة لكل سؤال.",
    correctAnswer: "إجابة صحيحة",
    incorrectAnswer: "ليست الإجابة الصحيحة",
    previousLesson: "الدرس السابق",
    nextLesson: "الدرس التالي",
    completionReady: "اكتملت جميع متطلبات الدرس.",
    completionPending: "أكمل المتطلبات المتبقية الظاهرة أدناه.",
    linkError: "تعذر فتح هذا المصدر بأمان.",
    cachedHint: "تبقى الدروس المحمّلة سابقًا متاحة دون اتصال.",
  },
} as const;

export type AcademyCopyKey = keyof typeof academyCopy.en;

export function academyText(locale: MobileLocale, key: AcademyCopyKey) {
  return academyCopy[locale][key];
}

const levelLabels: Record<MobileAcademyLevel, Record<MobileLocale, string>> = {
  beginner: { en: "Beginner", ar: "مبتدئ" },
  intermediate: { en: "Intermediate", ar: "متوسط" },
  advanced: { en: "Advanced", ar: "متقدم" },
  ict: { en: "ICT", ar: "مفاهيم ICT" },
  psychology: { en: "Trading psychology", ar: "علم نفس التداول" },
  "risk-management": { en: "Risk management", ar: "إدارة المخاطر" },
};

const difficultyLabels: Record<MobileLessonDifficulty, Record<MobileLocale, string>> = {
  easy: { en: "Easy", ar: "سهل" },
  medium: { en: "Medium", ar: "متوسط" },
  hard: { en: "Hard", ar: "صعب" },
  expert: { en: "Expert", ar: "خبير" },
};

export function academyLevelLabel(level: MobileAcademyLevel, locale: MobileLocale) {
  return levelLabels[level][locale];
}

export function academyDifficultyLabel(difficulty: MobileLessonDifficulty, locale: MobileLocale) {
  return difficultyLabels[difficulty][locale];
}
